apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimonedas-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apimonedas
  template:
    metadata:
      labels:
        app: apimonedas
    spec:
      containers:
        - name: apimonedas-c
          image: racso534/apimonedas-v1:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: apimonedas-cm
            - secretRef:
                name: bdmonedas-secretos